Starting architecture in premikanje ladje
ethernal12/space_invaders-pygame-win_curses pull request #5
Opened 2023-02-26 18:47 UTC by ethernal12

Pull request za #1 #2 . @urosjarc

2023-02-26 22:20 UTC, urosjarc requested changes

2023-02-26 22:20 UTC, urosjarc commented on src/app/GUI.py
> +    def omejitev_pozicije(self):
Samo funkcije ki so implementirane od abstraktnega class-a App smejo biti public vse ostale morajo biti privat in ne smejo biti vidne zunaj classa.

2023-02-26 22:20 UTC, urosjarc commented on src/app/GUI.py
> +    def konec(self):
Manjka return type.

2023-02-26 22:20 UTC, urosjarc commented on src/app/GUI.py
> +        ladja = pygame.image.load("src/domain/ladja.png")
Hkrati naj še omenim da naj bodo v domeni samo domenski prostori, slika spada v app zaradi tega ker consola tega ne bo uporabljala. Predlagam da narediš tak direktorji...

- data
  - media
     - ladja.png  <- Slika ladje ne spada v src direktorij, notri naj bo samo source koda.
- src
  - ...
  - domain
     - ...

2023-02-26 22:20 UTC, urosjarc commented on src/domain/ladja.py
> +    velikost_x: float
Vsi domenski objekti... `Ladja`, `Strel`, `Vesoljci` imajo propertije `x` in `y`. Zato ustvari domenski class `Objekt` in naj vsi elementi podedujejo od tega objekta da bodo podedovali njegove lastnosti.

Tako boš stvari pripravil da če boš hotel da vsi objekti imajo naprimer hitrost ti ne bo treba duplicirati kode.

2023-02-26 22:20 UTC, urosjarc commented on test/domain/test_ladja.py
> +        self.assertEqual(self.ladja.x, stari_x - self.ladja.hitrost)
Preveč explicitno testiraš... Testiraš če se je ladja dejansko premaknila levo, ne pa testirat za koliko točno se je premaknila v levo.

2023-02-26 22:20 UTC, urosjarc commented on test/domain/test_ladja.py
> +        self.assertEqual(self.ladja.x, stari_x + self.ladja.hitrost)
Enaki komentarji kot pri `def test_desno`.

2023-02-27 15:30 UTC, ethernal12 commented
@urosjarc Popravki narejeni.

2023-02-27 18:43 UTC, urosjarc approved these changes

2023-02-27 18:43 UTC, urosjarc commented on src/app/GUI.py
> +    def konec(self) -> None:
Ta funkcija mora drugače `bool (True)` vračat ampak dobro ni panike zaenkrat, ne bom pedanten.

2023-02-27 18:43 UTC, merged